# IO Settings
positionfile: angle.xyz
bondfile: bonds.dat
# Output settings
outputfile:
    filename: output.xyz
    frequency: 1000

#Simulation settings
simulation:
    timestep: 1.4
    steps: 5000000

excitements:
    - atoms: [Au%1, C%1]
      factor: 1.2
    - atoms: [C%1, O%1]
      factor: 1.2
